name: ""
services:
    app:
        container_name: App
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                TIMEZONE: '${APP_TIMEZONE:-UTC}'
        environment:
            HEALTHCHECK_PATH: '/up' #make sure this is aligned with the health path in bootstrap/app.php
            PHP_UPLOAD_MAX_FILE_SIZE: '100M'
            PHP_POST_MAX_SIZE: '100M'
            NGINX_FASTCGI_BUFFERS: '128 4k'
            NGINX_FASTCGI_BUFFER_SIZE: '32k'
            PHP_OPCACHE_ENABLE: '1'
            AUTORUN_ENABLED: 'true'
            AUTORUN_DEBUG: '${APP_ENV:-true}'
            AUTORUN_LARAVEL_MIGRATION_DATABASE: '${AUTORUN_LARAVEL_MIGRATION_DATABASE:-mariadb}'
            AUTORUN_LARAVEL_CONFIG_CACHE: '${AUTORUN_LARAVEL_CONFIG_CACHE:-false}'
            AUTORUN_LARAVEL_EVENT_CACHE: '${AUTORUN_LARAVEL_EVENT_CACHE:-false}'
            AUTORUN_LARAVEL_OPTIMIZE: '${AUTORUN_LARAVEL_OPTIMIZE:-false}'
            AUTORUN_LARAVEL_ROUTE_CACHE: '${AUTORUN_LARAVEL_ROUTE_CACHE:-false}'
            AUTORUN_LARAVEL_VIEW_CACHE: '${AUTORUN_LARAVEL_VIEW_CACHE:-false}'
            AUTORUN_LARAVEL_MIGRATION_SEED: '${AUTORUN_LARAVEL_MIGRATION_SEED:-false}'
        ports:
            - '${APP_PORT:-8080}:8080'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - .:/var/www/html
        networks:
            - zepeed
        depends_on:
            mariadb:
                condition: service_healthy
            mailpit:
                condition: service_healthy
    mariadb:
        container_name: Mariadb
        image: 'mariadb:11'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ROOT_HOST: '${DB_HOST:-%}'
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: '1'
            MARIADB_EXTRA_FLAGS: '--innodb-use-native-aio=0'
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        volumes:
            - 'zepeed-mariadb:/var/lib/mysql'
        networks:
            - zepeed
    mailpit:
        container_name: Mailpit
        image: 'axllent/mailpit:latest'
        ports:
            - "8025:8025" # Web UI
            - "1025:1025" # SMTP
        healthcheck:
            test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:8025/api/v1/info" ]
            interval: 30s
            timeout: 5s
            retries: 3
            start_period: 5s
        networks:
            - zepeed
networks:
    zepeed:

volumes:
    zepeed-mariadb:
        driver: local
