#!/command/with-contenv sh
# $1 = exit code of run, $2 = signal number that caused exit (or 256 if not signal)
if [ "${1}" -ne 0 ] && [ "${1}" -ne 256 ]; then
    echo "[queue-worker] exited with code ${1}, signal ${2} — restarting"
fi
